export const ROOT_API = 'http://ec2-18-222-196-130.us-east-2.compute.amazonaws.com:8080'; // aws
// export const ROOT_API = 'http://localhost:8080'; // local

export const CLEAR_FIELD = "CLEAR_FIELD"

export const FETCH_USER = "FETCH_USER"
export const REGISTER_USER = "REGISTER_USER"
export const DELETE_USER = "DELETE_USER"
export const FETCH_EDIT_USER = "FETCH_EDIT_USER"
export const EDIT_USER = "EDIT_USER"


export const FETCH_LEAVE_PENDING = "FETCH_LEAVE_PENDING"
export const FETCH_LEAVE_APPROVE = "FETCH_LEAVE_APPROVE"
export const FETCH_LEAVE_REJECT = "FETCH_LEAVE_REJECT"


export const FETCH_REQUEST_PENDING = "FETCH_REQUEST_PENDING"
export const DELETE_REQUEST_PENDING = "DELETE_REQUEST_PENDING"
export const EDIT_REQUEST_PENDING = "EDIT_REQUEST_PENDING"
export const FETCH_REQUEST_APPROVE = "FETCH_REQUEST_APPROVE"
export const FETCH_REQUEST_REJECT = "FETCH_REQUEST_REJECT"


export const APPROVE_LEAVE_PENDING = "APPROVE_LEAVE_PENDING"
export const REJECT_LEAVE_PENDING = "REJECT_LEAVE_PENDING"
export const CANCEL_LEAVE_REQUEST = "CANCEL_LEAVE_REQUEST"


export const FETCH_USER_SUMMARY = "FETCH_USER_SUMMARY"
export const FETCH_TYPE_LEAVE = "FETCH_TYPE_LEAVE"


export const LOGIN_FORM_ONCHANGE = "LOGIN_FORM_ONCHANGE"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const GET_PROFILE = "GET_PROFILE"
export const EDIT_PASSWORD = "EDIT_PASSWORD"

export const GET_SUPERVISORS = "GET_SUPERVISORS"

export const CREATE_LEAVE_REQUEST = "CREATE_LEAVE_REQUEST"

export const FETCH_LEAVE_BALANCES = "FETCH_LEAVE_BALANCES"
